<?php


namespace NewPlayerMC\Solarite\blocks;


use pocketmine\block\BlockToolType;
use pocketmine\event\Listener;
use pocketmine\item\Item;
use pocketmine\item\TieredTool;

class RandomOre extends \pocketmine\block\Solid
{
    protected $id = 236;
    protected $meta = 15;

    public function __construct()
    {
        parent::__construct(236, 15, "RandomOre", 278);
    }

    public function getName(): string
    {
        return "RandomOre"; // TODO: Change the autogenerated stub
    }
    public function getHardness(): float
    {
        return 4; // TODO: Change the autogenerated stub
    }

    public function getToolType(): int
    {
        return BlockToolType::TYPE_PICKAXE; // TODO: Change the autogenerated stub
    }

    public function getToolHarvestLevel(): int
    {
        return TieredTool::TIER_DIAMOND; // TODO: Change the autogenerated stub
    }

    public function getXpDropForTool(Item $item): int
    {
        return rand(7, 8); // TODO: Change the autogenerated stub
    }

    public function getDropsForCompatibleTool(Item $item) : array{
        $rand = rand(1, 10);
        if($rand === 1) {
            return [Item::get(Item::GOLD_INGOT, 0, 1)];
        } elseif ($rand >= 2 && $rand <= 4) {
            return [Item::get(264, 0, 1)];
        } elseif ($rand >= 5 && $rand <= 7) {
            return [Item::get(Item::IRON_INGOT, 0, rand(1, 2))];
        } elseif ($rand >= 8 && $rand <= 10) {
            return [Item::get(263, 0, rand(2, 3))];
        }
    }

}