<?php


namespace NewPlayerMC\Solarite\entity;


use pocketmine\block\Block;
use pocketmine\level\Level;
use pocketmine\level\particle\HugeExplodeParticle;
use pocketmine\math\RayTraceResult;
use pocketmine\Player;
use pocketmine\level\particle\CriticalParticle;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\entity\Projectile;
use pocketmine\entity\Entity;
use pocketmine\level\Explosion;
use pocketmine\event\entity\ExplosionPrimeEvent;

class Fireball extends \pocketmine\entity\projectile\Throwable
{
    const NETWORK_ID = self::FIREBALL;

    public $width = 5;
    public $height = 5;

    protected $gravity = 0;


    public function getName()
    {
        return "Fire Ball";
    }

    public function onHitBlock(Block $blockHit, RayTraceResult $hitResult): void
    {
        parent::onHitBlock($blockHit, $hitResult); // TODO: Change the autogenerated stub
        $this->getLevel()->addParticle(new HugeExplodeParticle($this->asVector3())); //TODO: FAKE EXPLOSIVE.
    }

    protected function onHitEntity(Entity $entityHit, RayTraceResult $hitResult): void
    {
        parent::onHitEntity($entityHit, $hitResult); // TODO: Change the autogenerated stub
        $this->getLevel()->addParticle(new HugeExplodeParticle($this->asVector3())); //TODO: FAKE EXPLOSIVE.
    }

    public function onUpdate(int $currentTick): bool
    {
        if ($this->closed) {
            return false;
        }

        $this->timings->startTiming();
        $this->updateMovement();
        $hasUpdate = parent::onUpdate($currentTick);

        if ($this->ticksLived > 200 or $this->isCollided)
        {
            $explosion = new Explosion($this->asPosition(), 3);
            $explosion->explodeB();
            $this->flagForDespawn();
            $hasUpdate = true;
        }

        $this->timings->stopTiming();

        return $hasUpdate;
    }

}